#!/usr/bin/env python3
"""
Convert icons_comfy/*.png → tft_icon_test/icons_tft.h (RGB565 arrays for ST7735).

Usage:
    python3 tools/icons_to_h.py

Requires: Pillow  (pip install pillow)
"""

import re
from pathlib import Path
from PIL import Image

ICONS_DIR = Path(__file__).parent / "icons_comfy"
OUT_DIR   = Path(__file__).parent / "tft_icon_test"
OUT_H     = OUT_DIR / "icons_tft.h"

# Only real icons, not previews / raw
SKIP_SUFFIX = ("_preview.png", "_raw.png")


def to_rgb565(r: int, g: int, b: int, a: int) -> int:
    """RGBA → RGB565. Transparent pixels (a < 128) → 0x0000 (black bg)."""
    if a < 128:
        return 0x0000
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(path: Path):
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    vals = []
    for y in range(h):
        for x in range(w):
            vals.append(to_rgb565(*img.getpixel((x, y))))
    return w, h, vals


def c_name(stem: str) -> str:
    """ic32_speed → ic32_speed  (already valid C identifier)"""
    return re.sub(r"[^0-9A-Za-z_]", "_", stem)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    pngs = sorted(
        p for p in ICONS_DIR.glob("*.png")
        if not any(str(p).endswith(s) for s in SKIP_SUFFIX)
    )

    if not pngs:
        print(f"No icons found in {ICONS_DIR}")
        return

    # Group by size for the header comment
    groups: dict[int, list] = {}
    entries = []
    for path in pngs:
        w, h, vals = convert(path)
        name = c_name(path.stem)
        entries.append((name, w, h, vals))
        groups.setdefault(w, []).append(name)
        print(f"  {path.name:35s} → {name}[{w}×{h}]")

    lines = [
        "// Auto-generated by tools/icons_to_h.py — DO NOT EDIT",
        "// Icons converted from tools/icons_comfy/*.png",
        "// Format: RGB565, transparent pixels → 0x0000 (black)",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]

    for name, w, h, vals in entries:
        lines.append(f"// {name}: {w}×{h}")
        lines.append(f"static const uint16_t {name}[{w * h}] = {{")
        # 16 values per row
        for i in range(0, len(vals), 16):
            chunk = vals[i:i + 16]
            lines.append("  " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
        lines.append("};")
        lines.append("")

    # Convenience struct array per size
    for size in sorted(groups.keys(), reverse=True):
        names = groups[size]
        lines.append(f"// ── {size}×{size} icon list ──────────────────────────────")
        lines.append(f"struct IconEntry_{size} {{ const uint16_t* data; const char* name; }};")
        lines.append(f"static const IconEntry_{size} ICONS_{size}[] = {{")
        for n in names:
            short = n.split("_", 1)[1] if "_" in n else n   # "ic32_speed" → "speed"
            # Do NOT truncate: these strings are the lookup keys used by findIcon*(), and
            # clipping them to 6 chars silently broke every name longer than that
            # ("settings" was emitted as "settin", so findIcon32("settings") found nothing
            # and the Settings tile simply rendered with no icon at all).
            lines.append(f'  {{ {n}, "{short}" }},')
        lines.append("};")
        lines.append(f"static const int N_{size} = {len(names)};")
        lines.append("")

    OUT_H.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nDone → {OUT_H}  ({len(entries)} icons)")

    # Summary
    for size, names in sorted(groups.items(), reverse=True):
        print(f"  {size:3d}×{size}: {len(names)} icons  ({', '.join(n.split('_',1)[1] if '_' in n else n for n in names)})")


if __name__ == "__main__":
    main()
